/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista;

import controlador.DAO.EleccionDao;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelo.Candidato;

public class FrmEleccion extends javax.swing.JDialog {
    private EleccionDao eleccionDao = new EleccionDao();
    private Integer id_papeleta;
    private Candidato candidato;

    /**
     * Creates new form FrmEleccion
     */
    public FrmEleccion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
    }
    
    public FrmEleccion(java.awt.Frame parent, boolean modal, Integer id_papeleta, Candidato candidato) {
        super(parent, modal);
        initComponents();
        this.id_papeleta = id_papeleta;
        this.candidato = candidato;
        this.lblCandidato.setText(candidato.getNombre_candidato());
        this.setVisible(true);
    }
    
    
    private void votar() throws IOException{
        if (rbtnSufragarCandidato.isSelected()) {
//            votoDao.getVoto().setSeleccionado(true);
            JOptionPane.showMessageDialog(this, "Sufragado");
        }else if(rbtnNulo.isSelected()){
//            votoDao.getVoto().setNulo(true);
            JOptionPane.showMessageDialog(this, "Nulo");
        }else{
//            votoDao.getVoto().setBlanco(true);
            JOptionPane.showMessageDialog(this, "Blanco");
        }
//        eleccionDao.getEleccion().setVoto(votoDao.getVoto());
//        eleccionDao.getEleccion().setId_papeleta(id_papeleta);
        //eleccionDao.guardar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbtngEleccion = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        rbtnSufragarCandidato = new javax.swing.JRadioButton();
        lblCandidato = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        rbtnEnBlanco = new javax.swing.JRadioButton();
        rbtnNulo = new javax.swing.JRadioButton();
        btnVotar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Eleccion"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rbtngEleccion.add(rbtnSufragarCandidato);
        rbtnSufragarCandidato.setText("Sufragar");
        jPanel2.add(rbtnSufragarCandidato, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, -1, -1));

        lblCandidato.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCandidato.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCandidato.setText("CANDIDATO");
        jPanel2.add(lblCandidato, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 30, 470, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Otros"));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rbtngEleccion.add(rbtnEnBlanco);
        rbtnEnBlanco.setText("En blanco");
        jPanel3.add(rbtnEnBlanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        rbtngEleccion.add(rbtnNulo);
        rbtnNulo.setText("Nulo");
        jPanel3.add(rbtnNulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, -1, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 460, 100));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 480, 250));

        btnVotar.setText("Votar");
        btnVotar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVotarActionPerformed(evt);
            }
        });
        jPanel1.add(btnVotar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVotarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVotarActionPerformed
        try {
            // TODO add your handling code here:
            votar();
            this.dispose();
        } catch (IOException ex) {
            Logger.getLogger(FrmEleccion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnVotarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmEleccion dialog = new FrmEleccion(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVotar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblCandidato;
    private javax.swing.JRadioButton rbtnEnBlanco;
    private javax.swing.JRadioButton rbtnNulo;
    private javax.swing.JRadioButton rbtnSufragarCandidato;
    private javax.swing.ButtonGroup rbtngEleccion;
    // End of variables declaration//GEN-END:variables
}
