/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.DAO.VotoDao;
import javax.swing.JOptionPane;
import vista.ModeloTabla.ModeloTablaVoto;
import vista.Utilidades.Utilidades;
import javax.swing.JLabel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import java.awt.Image;  
import javax.swing.JComboBox;
import java.util.Date;
/**
 *
 * @author wilson7578
 */
public class FrmVoto extends javax.swing.JDialog {
    VotoDao vd = new VotoDao();
    ModeloTablaVoto modelo  = new ModeloTablaVoto();
    int fila = -1 ;
    Utilidades u = new Utilidades();
    
    /**
     * Creates new form FrmVoto
     */
    public FrmVoto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cargarTabla();
       cargarImagenes();
      cargaCombo();
    }
 /**
 * Este método se encarga de cargar imágenes en etiquetas del formulario.
 * Realiza las siguientes acciones:
 * 
 * - Establece la ubicación relativa del formulario utilizando 'this.setLocationRelativeTo(this)'.
 * - Asigna imágenes a las etiquetas utilizando el método 'SetImageLabel()' con las rutas de archivo correspondientes.
 * 
 * Las imágenes se cargan en las etiquetas 'jblvoto1', 'jblestado', 'jblubicacion' y 'jblVoto',
 * brindando una representación visual para las diferentes partes del formulario.
 */
    public void cargarImagenes(){
     this.setLocationRelativeTo(this);
        SetImageLabel(jblvoto1, "C:\\Users\\Gonzalez G\\OneDrive\\Desktop\\PROYECTO DE VOTACION\\PIS\\PIS_PROYECTO\\src\\imagenes\\voto.png");
        SetImageLabel(jblestado, "C:\\Users\\Gonzalez G\\OneDrive\\Desktop\\PROYECTO DE VOTACION\\PIS\\PIS_PROYECTO\\src\\imagenes\\estadovoto.png");
        SetImageLabel(jblubicacion, "C:\\Users\\Gonzalez G\\OneDrive\\Desktop\\PROYECTO DE VOTACION\\PIS\\PIS_PROYECTO\\src\\imagenes\\ubicacion.png");
        SetImageLabel(jblVoto, "C:\\Users\\Gonzalez G\\OneDrive\\Desktop\\PROYECTO DE VOTACION\\PIS\\PIS_PROYECTO\\src\\imagenes\\votocolor.png");
    
    }
/**
 * Este método se encarga de establecer una imagen en una etiqueta específica del formulario.
 * Realiza las siguientes acciones:
 * 
 * - Crea un objeto ImageIcon utilizando la ruta de archivo proporcionada.
 * - Escala la imagen para que se ajuste al tamaño de la etiqueta utilizando 'getScaledInstance()'.
 * - Crea un Icon utilizando la imagen escalada.
 * - Establece el icono en la etiqueta especificada utilizando 'labelName.setIcon()'.
 * - Repinta el formulario para actualizar la representación visual.
 * 
 * @param labelName La etiqueta donde se establecerá la imagen.
 * @param root La ruta de archivo de la imagen a cargar.
 */
       private void SetImageLabel(JLabel labelName, String root) {
        ImageIcon image = new ImageIcon(root);
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(labelName.getWidth(), labelName.getHeight(), Image.SCALE_DEFAULT));
        labelName.setIcon(icon);
        this.repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbxEstado = new javax.swing.JComboBox<>();
        cbxTipo = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jblVoto = new javax.swing.JLabel();
        jblestado = new javax.swing.JLabel();
        jblvoto1 = new javax.swing.JLabel();
        jblubicacion = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTabla = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(131, 175, 155)));

        jLabel1.setText("Tipo de voto");

        jLabel3.setText("Estado");

        cbxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TRUE", "FALSE" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jblVoto, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jblVoto, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel5.setText("REGISTRO DE VOTO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cbxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(70, 70, 70)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jblubicacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jblvoto1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jblestado, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jblvoto1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jblestado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jblubicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 14, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbxEstado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(68, 68, 68)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tblTabla.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(131, 175, 155)));
        tblTabla.setAutoscrolls(false);
        jScrollPane1.setViewportView(tblTabla);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
 * Este método se encarga de cargar los datos de los votos en una tabla en el formulario.
 * Realiza las siguientes acciones:
 * 
 * - Obtiene una lista de votos utilizando el método 'listar()' del objeto 'vd'.
 * - Establece la lista de votos en el modelo de la tabla utilizando 'modelo.setLista()'.
 * - Asigna el modelo de la tabla a la tabla 'tblTabla' utilizando 'tblTabla.setModel()'.
 * - Actualiza la interfaz de usuario de la tabla utilizando 'tblTabla.updateUI()'.
 * 
 * Este método actualiza la tabla con los datos más recientes de los votos, lo que permite
 * que el usuario vea y manipule la información actualizada.
 */
    
    private void cargarTabla() {
        modelo.setLista(vd.listar());
        tblTabla.setModel(modelo);
        tblTabla.updateUI();

    }
    
    private void cargaCombo(){
    Utilidades.cargarComboTipoVoto(cbxTipo);
    }
/**
 * Este método se encarga de guardar la información de un voto en el sistema.
 * Verifica que se hayan ingresado los campos necesarios y realiza las operaciones
 * correspondientes para almacenar el voto en la base de datos.
 * 
 * Luego, establece el tipo de voto, el estado y la fecha de emisión del voto en
 * función de las selecciones del usuario y la fecha actual.
 * 
 * Si el ID del voto no es nulo, indica que se está modificando un voto existente.
 * En ese caso, llama al método 'modificar()' del objeto 'vd' con la fila especificada
 * y luego limpia los campos de entrada utilizando el método 'limpiar()'.
 * 
 * Si el ID del voto es nulo, indica que se está creando un nuevo voto.
 * Llama al método 'guardar()' del objeto 'vd' para guardar el nuevo voto en la base
 * de datos y luego limpia los campos de entrada utilizando el método 'limpiar()'.
 * 
 * Finalmente, muestra un mensaje indicando que se ha guardado la información de forma
 * exitosa, o muestra un mensaje de error si ocurre una excepción durante el proceso.
 */
     public void guardar() {
         
         if ( cbxTipo.getSelectedItem().toString().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese todo los campos", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                vd.getVoto().setTipoVoto(Utilidades.getComboTipoVoto(cbxTipo));                 
                vd.getVoto().setEstado(cbxEstado.getSelectedItem().equals("TRUE"));
                vd.getVoto().setFechade_emision(u.generarFechaActual());
                System.out.println();
                if (vd.getVoto().getId() != null) {
                    vd.modificar(fila);
                    limpiar();
                } else {
                   
                        vd.guardar();
                    limpiar();
                }
                    
                
                JOptionPane.showMessageDialog(null, "Se ha guardado de forma correcta", "OK", JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
         
    }
/**
 * Este método se encarga de restablecer el formulario a su estado original después de
 * que se haya guardado un voto o se haya cancelado una operación. Realiza las siguientes
 * acciones:
 * 
 * - Establece el objeto de voto en 'null' en el objeto 'vd'.
 * - Reinicia el valor de la variable 'fila' a -1, indicando que no se ha seleccionado ninguna fila.
 * - Llama al método 'cargarTabla()' para volver a cargar los datos en la tabla del formulario.
 * 
 * Este método es útil para limpiar los campos y preparar el formulario para un nuevo voto
 * o para realizar otra operación.
 */
       private void limpiar() {
        this.vd.setVoto(null);
        fila = -1;
        cargarTabla();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmVoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmVoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmVoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmVoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmVoto dialog = new FrmVoto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbxEstado;
    private javax.swing.JComboBox<String> cbxTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jblVoto;
    private javax.swing.JLabel jblestado;
    private javax.swing.JLabel jblubicacion;
    private javax.swing.JLabel jblvoto1;
    private javax.swing.JTable tblTabla;
    // End of variables declaration//GEN-END:variables
}
