package vista;

import controlador.DAO.DignidadDao;
import controlador.DAO.PartidoPoliticoDao;
import controlador.ed.listas.exception.ListaNullException;
import controlador.ed.listas.exception.PosicionNoEncontradaException;
import modelo.Candidato;

public class pnCandidatos extends javax.swing.JPanel {

    private PartidoPoliticoDao daoPartido = new PartidoPoliticoDao();
    private DignidadDao daoDignidad = new DignidadDao();
    
    public pnCandidatos() {
        initComponents();
    }
    
    public void setInfo(Candidato uno, Candidato dos){
        try {
            lbNombrePartido.setText(daoPartido.buscarPorId(uno.getId_partido_politico()).getNombre_partido_politico());
            lbDignidadUno.setText(daoDignidad.buscarPorId(uno.getId_dignidad()).getTipo());
            lbNombreDigUno.setText(uno.getNombre_candidato());
            lbDignidadDos.setText(daoDignidad.buscarPorId(dos.getId_dignidad()).getTipo());
            lbNombreDigDos.setText(dos.getNombre_candidato());
        } catch (ListaNullException | PosicionNoEncontradaException ex) {
        } catch (Exception ex) {
        }
    }
    
    
    
    public boolean check(){
        return checkCandidato.isSelected();
    }

    public String nombreDig(){
        return lbDignidadUno.getText();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbNombrePartido = new javax.swing.JLabel();
        lbDignidadUno = new javax.swing.JLabel();
        lbNombreDigUno = new javax.swing.JLabel();
        lbDignidadDos = new javax.swing.JLabel();
        lbNombreDigDos = new javax.swing.JLabel();
        checkCandidato = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbNombrePartido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbNombrePartido.setText("NOMBRE DEL PARTIDO");

        lbDignidadUno.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbDignidadUno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDignidadUno.setText("DIGNIDAD");

        lbNombreDigUno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbNombreDigUno.setText("NOMBRE DEL CANDIDATO");

        lbDignidadDos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbDignidadDos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDignidadDos.setText("DIGNIDAD");

        lbNombreDigDos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbNombreDigDos.setText("NOMBRE DEL CANDIDATO");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/icon/candidato3.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbNombrePartido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbNombreDigUno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbDignidadUno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbNombreDigDos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbDignidadDos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                        .addComponent(checkCandidato)
                        .addGap(79, 79, 79)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbNombrePartido)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(lbDignidadUno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbNombreDigUno)
                .addGap(20, 20, 20)
                .addComponent(lbDignidadDos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbNombreDigDos)
                .addGap(20, 20, 20)
                .addComponent(checkCandidato)
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkCandidato;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbDignidadDos;
    private javax.swing.JLabel lbDignidadUno;
    private javax.swing.JLabel lbNombreDigDos;
    private javax.swing.JLabel lbNombreDigUno;
    private javax.swing.JLabel lbNombrePartido;
    // End of variables declaration//GEN-END:variables
}
